model_lang: en-us

model_default_temperature: 1.0
default_llm_service: gemini
default_model:
  gemini: gemini-2.0-flash
  grok: grok-3-mini-fast-beta
default_embedding_service: gemini
default_embedding_model:
  gemini: embedding-001

enable_timestamp_prompt: true
enable_weather_period_prompt: true